import type { Metadata } from "next";
import { Handjet, Inter, Lato, Exo_2, Lexend } from "next/font/google";
import "./globals.css";
import AuthState from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
import MobileNavigation from "@/components/web/navigation/mobile_navigation";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const lexend = Lexend({
    subsets: ["latin"],
    weight: ["400", "700"],
});

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthState>
            <html lang="en">
                <body className={lexend.className}>
                    <div className="absolute bottom-8 left-1/2 ">
                        <Toaster />
                    </div>
                    <MobileNavigation />
                    {children}
                </body>
            </html>
        </AuthState>
    );
}
